[package]
name = "w-usecase"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.0", features = ["rt-multi-thread", "macros"] }
serde = "*"
serde_json = "*"
itertools = "*"
csv = "*"
