[package]
name = "w-external-api"
version = "0.1.0"
edition = "2021"

[dependencies]
w-config = { path = "../w-config" }

reqwest = { version = "0.11", features = ["json"] }
serde_json = "*"
anyhow = "*"
tokio = { version = "1.20.0" }
strum = "0.25.0"
strum_macros = "0.25"
